name: Deploy Token to Base Mainnet

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      RPC_URL: ${{ secrets.BASE_RPC_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat run deploy/deploy-token.js --network base
