name: Dotenvx Secrets Sync

on:
  push:
    branches: [main]
    paths:
      - '.env*'
  workflow_dispatch:

jobs:
  cloak-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dotenvx CLI
        run: curl -sfS https://dotenvx.sh/pro | sh

      - name: Encrypt & Cloak `.env.production`
        run: |
          dotenvx encrypt -f .env.production
          dotenvx pro cloak -f .env.production

      - name: Commit Cloaked Secrets
        run: |
          git config user.name "Boomchainlab CI Bot"
          git config user.email "dev@boomchainlab.com"
          git add .env.production.cloak
          git commit -m "chore(secrets): cloak .env.production via Dotenvx Pro" || echo "No changes to commit"
          git push origin main
